/**
 * PixInsight V8 TypeScript Build Pipeline
 * 
 * Supports both modular multi-file libraries (via esbuild bundling) and single-file scripts.
 * Automatically extracts and injects #engine v8 and preprocessor directives at Line 1.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const rootDir = path.resolve(__dirname, '..');
const srcDir = path.join(rootDir, 'src');
const distDir = path.join(rootDir, 'dist');
const isWatch = process.argv.includes('--watch') || process.argv.includes('-w');

function log(msg) {
    console.log(`\x1b[36m[PJSR Builder]\x1b[0m ${msg}`);
}

function logSuccess(msg) {
    console.log(`\x1b[32m[PJSR Builder SUCCESS]\x1b[0m ${msg}`);
}

function logError(msg) {
    console.error(`\x1b[31m[PJSR Builder ERROR]\x1b[0m ${msg}`);
}

/**
 * Extracts preprocessor headers from the original source .ts file.
 */
function extractHeaders(sourcePath) {
    if (!fs.existsSync(sourcePath)) return ['#engine v8'];
    const content = fs.readFileSync(sourcePath, 'utf8');
    const headers = [];
    const regex = /^\s*(?:\/\/)?\s*(#(?:engine|feature-id|feature-icon|feature-info|script-id|include|define|undef|if|ifdef|ifndef|else|endif).*)$/gm;
    let match;
    while ((match = regex.exec(content)) !== null) {
        headers.push(match[1].trim());
    }

    // Ensure #engine v8 is always first
    const cleanHeaders = headers.filter(h => !h.startsWith('#engine'));
    return ['#engine v8', ...cleanHeaders];
}

function build() {
    const start = Date.now();

    // 1. Type check
    log('Running TypeScript type check (tsc --noEmit)...');
    try {
        execSync('npx --package typescript tsc --noEmit', { cwd: rootDir, stdio: 'inherit' });
    } catch (err) {
        logError('Type check failed. Fix type errors above.');
        return false;
    }

    // 2. Clean dist
    if (fs.existsSync(distDir)) {
        fs.rmSync(distDir, { recursive: true, force: true });
    }
    fs.mkdirSync(distDir, { recursive: true });

    // 3. Find root entry scripts in src/*.ts (excluding subdirectories like src/lib/)
    const entryFiles = fs.readdirSync(srcDir, { withFileTypes: true })
        .filter(entry => entry.isFile() && entry.name.endsWith('.ts'))
        .map(entry => entry.name);

    if (entryFiles.length === 0) {
        log('No .ts entry scripts found in src/.');
        return true;
    }

    log(`Bundling ${entryFiles.length} entry script(s)...`);

    for (const fileName of entryFiles) {
        const entryPath = path.join(srcDir, fileName);
        const outFileName = fileName.replace(/\.ts$/, '.js');
        const outPath = path.join(distDir, outFileName);

        try {
            // Bundle using esbuild (inlining imported modules from src/lib/)
            execSync(
                `npx --package esbuild esbuild "${entryPath}" --bundle --target=es2022 --format=esm --outfile="${outPath}"`,
                { cwd: rootDir, stdio: 'pipe' }
            );

            // Read bundled JS
            let bundledCode = fs.readFileSync(outPath, 'utf8');

            // Strip any export { ... } statements generated by esbuild at end of bundle
            bundledCode = bundledCode.replace(/^\s*export\s*\{[^}]*\};?\s*$/gm, '');

            // Prepend preprocessor headers
            const headers = extractHeaders(entryPath);
            const finalCode = headers.join('\n') + '\n\n' + bundledCode.trimStart();

            fs.writeFileSync(outPath, finalCode, 'utf8');
            log(`Emitted bundled script -> \x1b[33mdist/${outFileName}\x1b[0m`);
        } catch (err) {
            logError(`Failed to bundle ${fileName}: ${err.message}`);
            return false;
        }
    }

    const elapsed = Date.now() - start;
    logSuccess(`Build completed in ${elapsed} ms.`);
    return true;
}

if (isWatch) {
    log('Starting in watch mode...');
    build();

    if (fs.existsSync(srcDir)) {
        let debounceTimer = null;
        fs.watch(srcDir, { recursive: true }, (eventType, filename) => {
            if (filename && filename.endsWith('.ts')) {
                clearTimeout(debounceTimer);
                debounceTimer = setTimeout(() => {
                    log(`File change detected: ${filename}. Rebuilding...`);
                    build();
                }, 100);
            }
        });
        log(`Watching for file changes in: src/`);
    }
} else {
    const success = build();
    process.exit(success ? 0 : 1);
}
